version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uk.gov.hmcts.reform:idam-client
    versions:
    - 2.0.0
