---
spring:
  main:
    allow-bean-definition-overriding: true

idam:
  api:
    url: 'http://localhost:5000'
  client:
    id: 'webshow'
    secret: 'AAAAAAAAAAAAAAAA'
    redirect_uri: 'http://localhost:8080/oauth2redirect'
    grant_type: 'password'
    scope: 'openid roles profile'

s2s:
  api:
    url: 'http://localhost:4502'
    secret: 'AAAAAAAAAAAAAAAA'
    serviceName: 'em_gw'
    ccdGwSecret: 'AAAAAAAAAAAAAAAA'
    ccdGwServiceName: 'ccd_gw'

ccd-def:
  api:
    url: 'http://localhost:4451'

document_management:
    url: 'http://localhost:4603'

core_case_data:
  api:
    url: 'http://localhost:4452'

case_document_am:
  url: 'http://localhost:4455'